// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.WebPConverter
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("inputFormat")]
        public string InputFormat { get; set; }

        [JsonProperty("outputFormat")]
        public string OutputFormat { get; set; }

        [JsonProperty("inputSize")]
        public long InputSize { get; set; }

        [JsonProperty("outputSize")]
        public long OutputSize { get; set; }

        [JsonProperty("mimeType")]
        public string MimeType { get; set; }

        [JsonProperty("expires")]
        public long Expires { get; set; }

        [JsonProperty("downloadURL")]
        public Uri DownloadUrl { get; set; }
    }
}
